Bookmark
SarahWett/quiz-app pull request #7
Opened 2023-01-20 07:28 UTC by SarahWett

Still missing functionality: 
JavaScript Coed doesn't work out switching unfilled - filled svgs.
Please review & you're welcome to share your ideas how to fix this issue! :)

2023-01-20 09:53 UTC, Kheirah requested changes
Good start! Have a look the comments and try adjusting your code to make it work :)

2023-01-20 09:53 UTC, Kheirah commented on index.html
> +      href="/Users/sw/Documents/Coding/DevelopmentNF/quiz-app/components/styles.css"
Local paths don't work on machines other than your own😄
Use relative or absolute paths in your project. The following should work:
```js
href="./components/styles.css"
```

2023-01-20 09:53 UTC, Kheirah commented on index.js
> +const bookmarkFilled = document.querySelector('[data-js="book_filled]');
```suggestion
const bookmarkUnfilled = document.querySelector('[data-js="book_unfilled"]');
const bookmarkFilled = document.querySelector('[data-js="book_filled"]');
```
You are missing double quotes.

2023-01-20 09:53 UTC, Kheirah commented on index.js
> +const bookmark3 = document.querySelector('[data-js="bookmark3"]');
I think what you want is this:
```suggestion
const bookmark1 = document.querySelector('[data-js="btn1"]');
const bookmark2 = document.querySelector('[data-js="btn2"]');
const bookmark3 = document.querySelector('[data-js="btn3"]');
```

2023-01-20 09:53 UTC, Kheirah commented on index.js
> +const bookmarkFilled = document.querySelector('[data-js="book_filled]');
Apart from the missing double quotes, you need to give your filled and unfilled bookmarks unique names.
```suggestion
const bookmark1Unfilled = document.querySelector('[data-js="book1_unfilled"]');
const bookmark1Filled = document.querySelector('[data-js="book1_filled"]');
```

2023-01-20 09:53 UTC, Kheirah commented on index.js
> +  bookmarkFilled.classList.toggle("off");
And then you need to use that unique name here and in the other functions.
```suggestion
  bookmark1Unfilled.classList.toggle("off");
  bookmark1Filled.classList.toggle("off");
```

2023-01-23 06:09 UTC, SarahWett commented on index.js
> +const bookmarkFilled = document.querySelector('[data-js="book_filled]');
oh yeah you're right - that seems to be the point! Missed that 'cause I thought a unique button would work the same way but that was surely odd! Thank you very much! :)

2023-01-23 07:42 UTC, closed without merging